/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package swelab;
import java.awt.Color;
import java.io.IOException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
/**
 *
 * @author 91861
 */
public class BandRUI extends javax.swing.JFrame {
    //private LoanManager mngr;
    

    /**
     * Creates new form BorrowandReturnUI
     */
    public BandRUI() {
        //this.mngr=mngr;
        initComponents();
        //mngr.readFile();
        //populateRecord(mngr.getLoan());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jT1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jT2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jT3 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jT4 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jT5 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("BookID");

        jT1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jT1ActionPerformed(evt);
            }
        });
        jT1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jT1KeyReleased(evt);
            }
        });

        jLabel2.setText("Title");

        jT2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jT2ActionPerformed(evt);
            }
        });
        jT2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jT2KeyReleased(evt);
            }
        });

        jLabel3.setText("ISBN no");

        jT3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jT3ActionPerformed(evt);
            }
        });
        jT3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jT3KeyReleased(evt);
            }
        });

        jLabel4.setText("Borrow Date");

        jT4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jT4ActionPerformed(evt);
            }
        });
        jT4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jT4KeyReleased(evt);
            }
        });

        jLabel5.setText("Return Date");

        jT5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jT5ActionPerformed(evt);
            }
        });
        jT5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jT5KeyReleased(evt);
            }
        });

        jButton1.setText("Borrow");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Return");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Due");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel6.setForeground(new java.awt.Color(255, 0, 51));

        jLabel7.setForeground(new java.awt.Color(255, 0, 51));

        jLabel8.setForeground(new java.awt.Color(255, 0, 51));

        jLabel9.setForeground(new java.awt.Color(255, 51, 51));
        jLabel9.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jLabel9KeyReleased(evt);
            }
        });

        jLabel10.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(269, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jT3, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE))
                        .addGap(23, 397, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jT2)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jT1, javax.swing.GroupLayout.DEFAULT_SIZE, 77, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jT5, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)
                            .addComponent(jT4)
                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(10, 10, 10))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jT1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jT4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jT2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jT5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jT3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(82, 82, 82)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 75, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addGap(32, 32, 32))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
         
             if(jT1.getText().length()>=0 && jT2.getText().length()>=0 && jT3.getText().length()>=0 && jT5.getText().length()>=0){
            JOptionPane.showMessageDialog(null,"Returned successfully at "+jT5.getText());
        }
        else {
            JOptionPane.showMessageDialog(null," ");
        }
      
       // mngr.BorrowandReturn(new Loan(this.jT1.getText()),this.jT2.getText(),this.jT3.getText(),this.jT4.getText(),this.jT5.getText());
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jT1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jT1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jT1ActionPerformed

    private void jT2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jT2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jT2ActionPerformed

    private void jT3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jT3ActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_jT3ActionPerformed

    private void jT4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jT4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jT4ActionPerformed

    private void jT5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jT5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jT5ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:mmgr.
          if(jT1.getText().trim().isEmpty() && jT2.getText().trim().isEmpty() && jT3.getText().trim().isEmpty() && jT4.getText().trim().isEmpty() && jT5.getText().trim().isEmpty())
        {
            jLabel6.setText("this field cannot be empty");
             jLabel7.setText("this field cannot be empty");
              jLabel8.setText("this field cannot be empty");
               jLabel9.setText("this field cannot be empty");
                jLabel10.setText("this field cannot be empty");
        }
       
        else if(jT1.getText().trim().isEmpty())
        {
            jLabel6.setText("this field cannot be empty");
        }
         else if(jT2.getText().trim().isEmpty())
        {
            jLabel7.setText("this field cannot be empty");
        }
         else if(jT3.getText().trim().isEmpty())
        {
            jLabel8.setText("this field cannot be empty");
        }
         else if(jT4.getText().trim().isEmpty())
        {
            jLabel9.setText("this field cannot be empty");
        }
         else if(jT5.getText().trim().isEmpty())
        {
            jLabel10.setText("this field cannot be empty");
        }
         else{
             if(jT1.getText().length()>=0 && jT2.getText().length()>=0 && jT3.getText().length()>=0 && jT4.getText().length()>=0){
            JOptionPane.showMessageDialog(null,"Borrowed successfully at "+jT4.getText());
        }
        else {
            JOptionPane.showMessageDialog(null," ");
        }
         }
        //mngr.BorrowandReturn(new Loan(this.jT1.getText()),this.jT2.getText(),this.jT3.getText(),this.jT4.getText(),this.jT5.getText());
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        if(jT1.getText().trim().isEmpty() && jT2.getText().trim().isEmpty() && jT3.getText().trim().isEmpty() && jT4.getText().trim().isEmpty() && jT5.getText().trim().isEmpty())
        {
            jLabel6.setText("this field cannot be empty");
            jLabel7.setText("this field cannot be empty");
            jLabel8.setText("this field cannot be empty");
            jLabel9.setText("this field cannot be empty");
            jLabel10.setText("this field cannot be empty");
        }
       
        else if(jT1.getText().trim().isEmpty())
        {
            jLabel6.setText("this field cannot be empty");
        }
        else if(jT2.getText().trim().isEmpty())
        {
            jLabel7.setText("this field cannot be empty");
        }
        else if(jT3.getText().trim().isEmpty())
        {
            jLabel8.setText("this field cannot be empty");
        }
        else if(jT4.getText().trim().isEmpty())
        {
            jLabel9.setText("this field cannot be empty");
        }
        else if(jT5.getText().trim().isEmpty())
        {
            jLabel10.setText("this field cannot be empty");
        }
        else{
            
            //mngr.calLoan(new Loan(this.jTextArea1.getText
            
            int due;
            int r_date=Integer.parseInt(jT5.getText());
            int b_date=Integer.parseInt(jT4.getText());
            int days=r_date-b_date;
            if(days>7)
            {
                due=(days-7)*10;
            }
            else
                due=0;
            System.out.print("Loan"+due);
        }
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jT1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jT1KeyReleased
        // TODO add your handling code here:
        jLabel6.setText("");
    }//GEN-LAST:event_jT1KeyReleased

    private void jT2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jT2KeyReleased
        // TODO add your handling code here:
        jLabel7.setText("");
    }//GEN-LAST:event_jT2KeyReleased

    private void jT3KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jT3KeyReleased
        // TODO add your handling code here:
        jLabel8.setText("");
    }//GEN-LAST:event_jT3KeyReleased

    private void jLabel9KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jLabel9KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel9KeyReleased

    private void jT5KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jT5KeyReleased
        // TODO add your handling code here
        jLabel10.setText("");
    }//GEN-LAST:event_jT5KeyReleased

    private void jT4KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jT4KeyReleased
        // TODO add your handling code here:
        jLabel9.setText("");
    }//GEN-LAST:event_jT4KeyReleased
private void populateRecord(List<Loan> loans){
    //Loan myLoan=loans.get(0);
   
     //this.jT1.setText(myLoan.getBookID());
      //this.jT2.setText(myLoan.getTitle());
       //this.jT3.setText(myLoan.getISBN_no());
        //this.jT4.setText(myLoan.getBorrow_Date());
         //this.jT5.setText(myLoan.getReturn_Date());
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        System.out.println("Thank you");
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        
        //</editor-fold>
        

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BandRUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jT1;
    private javax.swing.JTextField jT2;
    private javax.swing.JTextField jT3;
    private javax.swing.JTextField jT4;
    private javax.swing.JTextField jT5;
    // End of variables declaration//GEN-END:variables
}
