/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package swelab;

import java.awt.Toolkit;
import java.awt.event.WindowEvent;

/**
 *
 * @author prera
 */
public class Dashboard extends javax.swing.JFrame {

    /**
     * Creates new form Dashboard
     */
    public Dashboard() {
        
        initComponents();
        
    }
    public void close(){
    WindowEvent closeWindow = new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
    Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(closeWindow);
}
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Donateb = new javax.swing.JButton();
        Borrowb = new javax.swing.JButton();
        SearchB = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(null);

        Donateb.setBackground(new java.awt.Color(153, 153, 153));
        Donateb.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Donateb.setForeground(new java.awt.Color(153, 0, 0));
        Donateb.setIcon(new javax.swing.ImageIcon(getClass().getResource("/swelab/64x64.png"))); // NOI18N
        Donateb.setText("Donate");
        Donateb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DonatebActionPerformed(evt);
            }
        });
        jPanel1.add(Donateb);
        Donateb.setBounds(380, 110, 160, 70);

        Borrowb.setBackground(new java.awt.Color(153, 153, 153));
        Borrowb.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Borrowb.setForeground(new java.awt.Color(153, 0, 0));
        Borrowb.setIcon(new javax.swing.ImageIcon(getClass().getResource("/swelab/images (1).jpg"))); // NOI18N
        Borrowb.setText("Borrow/Return");
        Borrowb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BorrowbActionPerformed(evt);
            }
        });
        jPanel1.add(Borrowb);
        Borrowb.setBounds(200, 210, 220, 70);

        SearchB.setBackground(new java.awt.Color(153, 153, 153));
        SearchB.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        SearchB.setForeground(new java.awt.Color(153, 0, 0));
        SearchB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/swelab/search.png"))); // NOI18N
        SearchB.setText("Search");
        SearchB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchBActionPerformed(evt);
            }
        });
        jPanel1.add(SearchB);
        SearchB.setBounds(130, 110, 170, 73);

        jButton1.setText("Go Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(430, 310, 73, 23);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/swelab/blurred-bookshelf-many-old-books-260nw-1577682832.jpg"))); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(0, 0, 630, 370);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 630, 370));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DonatebActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DonatebActionPerformed
        // TODO add your handling code here:
       DonateBookui d1 = new d1();
            d1.show();
            dispose();
          
            
    }//GEN-LAST:event_DonatebActionPerformed

    private void SearchBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchBActionPerformed
        // TODO add your handling code here:
        SearchBook sb1 = new sb1();
            sb1.show();
            dispose();
    }//GEN-LAST:event_SearchBActionPerformed

    private void BorrowbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BorrowbActionPerformed
        // TODO add your handling code here:
        BandRUI br1 = new br1();
            br1.show();
            dispose();
        
    }//GEN-LAST:event_BorrowbActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        close();
        Login l2= new Login();
        l2.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Borrowb;
    private javax.swing.JButton Donateb;
    private javax.swing.JButton SearchB;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

    private static class sb1 extends SearchBook {

        public sb1() {
        }
    }

    private static class d1 extends DonateBookui {

        public d1() {
        }
    }

    private static class br1 extends BandRUI {

        public br1() {
        }
    }

    
        

        
    }

